<?php

/**
 * This file is part of the AIChatPageComponent plugin for ILIAS.
 *
 * Copyright (c) University of Cologne, CompetenceCenter E-Learning
 *
 * The plugin is licensed with the GPL-3.0,
 * see https://www.gnu.org/licenses/gpl-3.0.en.html
 * You should have received a copy of said license along with the
 * source code, too.
 */

declare(strict_types=1);

namespace ai;

use platform\AIChatPageComponentException;

require_once __DIR__ . '/class.AIChatPageComponentRAGBindingLostException.php';

/**
 * Client for the RAG WebGateway (document storage and retrieval)
 *
 * The RAG is independent of the AI service of a chat: it stores files and
 * retrieves relevant passages, the answer is generated by the AI service.
 *
 * Endpoints, all with "Authorization: Bearer <client key>":
 * - POST /v1/rag/upload        store a file in a collection
 * - POST /v1/rag/delete        delete a file and its chunks
 * - POST /v1/rag/augmentation  retrieval only: augmented messages and chunks
 *
 * The WebGateway derives the tenant from the client key.
 *
 * @author Nadimo Staszak <nadimo.staszak@uni-koeln.de>
 */
class AIChatPageComponentRAG
{
    private const ENDPOINT_UPLOAD = '/v1/rag/upload';

    private const ENDPOINT_DELETE = '/v1/rag/delete';

    private const ENDPOINT_STATUS = '/v1/rag/status';

    private const ENDPOINT_AUGMENTATION = '/v1/rag/augmentation';

    /** @var string Default RAG WebGateway URL */
    public const DEFAULT_API_URL = 'https://oski-rag.itcc.uni-koeln.de';

    /** @var string Default file types that are sent to the RAG */
    public const DEFAULT_FILE_TYPES = 'txt,csv,pdf';

    /** @var int Default maximum number of chunks selected by the reranker */
    public const DEFAULT_TOP_K = 10;

    /** Processing states reported by the RAG */
    public const STATUS_PENDING = 'PENDING';
    public const STATUS_PROCESSING = 'PROCESSING';
    public const STATUS_COMPLETED = 'COMPLETED';
    public const STATUS_FAILED = 'FAILED';

    /** @var string Exception message if the retrieval is temporarily unavailable (network error, HTTP 5xx) */
    public const UNAVAILABLE = 'rag_unavailable';

    private \ilLogger $logger;

    public function __construct()
    {
        global $DIC;
        $this->logger = $DIC->logger()->pcaic();
    }

    /**
     * RAG is usable if it is enabled and URL and client key are set
     */
    public static function isAvailable(): bool
    {
        if ((\platform\AIChatPageComponentConfig::get('rag_service_enabled') ?? '0') !== '1') {
            return false;
        }

        return self::getApiUrl() !== '' && self::getClientKey() !== '';
    }

    /**
     * Whether the administrator allows RAG for the AI service
     */
    public static function isEnabledForService(string $service_id): bool
    {
        $value = \platform\AIChatPageComponentConfig::get($service_id . '_enable_rag');
        return $value == '1' || $value === 1;
    }

    public static function getApiUrl(): string
    {
        $url = \platform\AIChatPageComponentConfig::get('rag_api_url');
        return rtrim(is_string($url) ? trim($url) : '', '/');
    }

    public static function getClientKey(): string
    {
        $key = \platform\AIChatPageComponentConfig::get('rag_client_key');
        return is_string($key) ? trim($key) : '';
    }

    /**
     * File types uploaded to the RAG; other types are sent to the AI service directly
     *
     * @return string[]
     */
    public static function getFileTypes(): array
    {
        $configured = \platform\AIChatPageComponentConfig::get('rag_allowed_file_types');
        if (is_array($configured)) {
            $configured = implode(',', $configured);
        }
        if (!is_string($configured) || trim($configured) === '') {
            $configured = self::DEFAULT_FILE_TYPES;
        }

        $types = array_values(array_filter(array_map(
            fn($type) => strtolower(trim($type)),
            explode(',', $configured)
        )));

        return $types ?: explode(',', self::DEFAULT_FILE_TYPES);
    }

    /**
     * @return array<string, \ILIAS\UI\Component\Input\Field\FormInput> Inputs of the RAG tab
     */
    public static function getConfigurationFormInputs(): array
    {
        global $DIC;
        $ui_factory = $DIC->ui()->factory();
        $plugin = \ilAIChatPageComponentPlugin::getInstance();

        $inputs = [];

        $enabled = \platform\AIChatPageComponentConfig::get('rag_service_enabled') ?? '0';
        $inputs['rag_service_enabled'] = $ui_factory->input()->field()->checkbox(
            $plugin->txt('config_rag_service_enabled'),
            $plugin->txt('config_rag_service_enabled_info')
        )->withValue($enabled === '1');

        $inputs['rag_api_url'] = $ui_factory->input()->field()->text(
            $plugin->txt('config_rag_api_url'),
            $plugin->txt('config_rag_api_url_info')
        )->withMaxLength(500)->withValue(self::getApiUrl() ?: self::DEFAULT_API_URL)->withRequired(true);

        $inputs['rag_client_key'] = $ui_factory->input()->field()->password(
            $plugin->txt('config_rag_client_key'),
            $plugin->txt('config_rag_client_key_info')
        )->withValue(self::getClientKey())->withRequired(true);

        $app_id = \platform\AIChatPageComponentConfig::get('rag_application_id');
        $inputs['rag_application_id'] = $ui_factory->input()->field()->text(
            $plugin->txt('config_rag_application_id'),
            $plugin->txt('config_rag_application_id_info')
        )->withMaxLength(100)->withValue((string) ($app_id ?: 'ILIAS'));

        $instance_id = \platform\AIChatPageComponentConfig::get('rag_instance_id');
        $inputs['rag_instance_id'] = $ui_factory->input()->field()->text(
            $plugin->txt('config_rag_instance_id'),
            $plugin->txt('config_rag_instance_id_info')
        )->withMaxLength(100)->withValue((string) ($instance_id ?: 'ilias9'));

        $inputs['rag_allowed_file_types'] = $ui_factory->input()->field()->text(
            $plugin->txt('config_rag_allowed_file_types'),
            $plugin->txt('config_rag_allowed_file_types_info')
        )->withMaxLength(500)->withValue(implode(',', self::getFileTypes()));

        $top_k = \platform\AIChatPageComponentConfig::get('rag_top_k');
        $inputs['rag_top_k'] = $ui_factory->input()->field()->numeric(
            $plugin->txt('config_rag_top_k'),
            $plugin->txt('config_rag_top_k_info')
        )->withValue($top_k !== null && $top_k !== '' ? (int) $top_k : self::DEFAULT_TOP_K);

        return $inputs;
    }

    public static function saveConfiguration(array $form_data): void
    {
        foreach ($form_data as $key => $value) {
            if ($value instanceof \ILIAS\Data\Password) {
                $value = $value->toString();
            }

            if (is_bool($value)) {
                $value = $value ? '1' : '0';
            }

            if ($key === 'rag_api_url' && is_string($value)) {
                $value = rtrim(trim($value), '/');
            }

            if ($key === 'rag_top_k') {
                $value = max(1, (int) ($value ?: self::DEFAULT_TOP_K));
            }

            \platform\AIChatPageComponentConfig::set($key, $value);
        }
    }

    public static function getDefaultConfiguration(): array
    {
        return [
            'rag_service_enabled' => '0',
            'rag_api_url' => self::DEFAULT_API_URL,
            'rag_client_key' => '',
            'rag_application_id' => 'ILIAS',
            'rag_instance_id' => 'ilias9',
            'rag_allowed_file_types' => self::DEFAULT_FILE_TYPES,
            'rag_top_k' => self::DEFAULT_TOP_K,
        ];
    }

    /**
     * @param string $entity_id Chat ID for background files, session ID for chat uploads
     * @param string|null $filename Name stored in the RAG and shown as source; defaults to the name of $filepath
     * @return array{collection_id: string, remote_file_id: string}
     * @throws AIChatPageComponentException
     */
    public function uploadFile(string $filepath, string $entity_id, ?string $filename = null): array
    {
        $this->assertConfigured();

        if (!file_exists($filepath)) {
            throw new AIChatPageComponentException("File not found: $filepath");
        }

        [$application_id, $instance_id, $entity_id_numeric] = self::getNumericIds($entity_id);

        $filename = ($filename !== null && trim($filename) !== '') ? basename(trim($filename)) : basename($filepath);
        // The RAG validates the extension, so fall back to the temp file name if the title has none
        if (pathinfo($filename, PATHINFO_EXTENSION) === '') {
            $filename = basename($filepath);
        }

        // Extension-based MIME mapping; the RAG validates extension + MIME together
        $ext_mime = [
            'pdf' => 'application/pdf',
            'html' => 'text/html',
            'txt' => 'text/plain',
            'png' => 'image/png',
            'jpg' => 'image/jpeg',
            'jpeg' => 'image/jpeg',
            'csv' => 'text/plain',
        ];
        $ext = strtolower(pathinfo($filename, PATHINFO_EXTENSION));
        if (isset($ext_mime[$ext])) {
            $mime_type = $ext_mime[$ext];
        } else {
            $finfo = finfo_open(FILEINFO_MIME_TYPE);
            $mime_type = finfo_file($finfo, $filepath);
            finfo_close($finfo);
        }

        $post_data = [
            'file' => curl_file_create($filepath, $mime_type, $filename),
            'applicationid' => $application_id,
            'instanceid' => $instance_id,
            'entityid' => $entity_id_numeric,
            'purpose' => 'assistants'
        ];

        $url = $this->getEndpointUrl(self::ENDPOINT_UPLOAD);
        $this->logger->debug("RAG Upload Request | file=$filename | ext=$ext | mime=$mime_type"
            . " | size=" . filesize($filepath) . " | url=$url");

        [$response, $http_code, $error] = $this->request($url, $post_data, [], 120);

        if ($response === false) {
            $this->logger->error("RAG file upload failed: cURL error - $error | file=$filename");
            throw new AIChatPageComponentException("RAG file upload failed: cURL error - $error");
        }

        $response_preview = substr((string) $response, 0, 500);
        $this->logger->debug("RAG Upload Response: HTTP $http_code | File: $filename | Response: $response_preview");

        if ($http_code !== 200) {
            $this->logger->error("RAG file upload failed: HTTP $http_code | file=$filename | " . substr($response_preview, 0, 300));
            throw new AIChatPageComponentException("RAG file upload failed: HTTP $http_code");
        }

        $data = json_decode((string) $response, true);
        if (!isset($data['collection_id']) || !isset($data['id'])) {
            $this->logger->error("Invalid RAG upload response structure: " . $response_preview);
            throw new AIChatPageComponentException("Invalid RAG response: missing collection_id or id");
        }

        $this->logger->info("File uploaded to RAG: collection_id=" . $data['collection_id'] .
            " | remote_file_id=" . $data['id'] . " | filename=" . $filename);

        return [
            'collection_id' => $data['collection_id'],
            'remote_file_id' => $data['id']
        ];
    }

    /**
     * Delete a file from the RAG
     *
     * The RAG answers HTTP 400 both for unknown files and for files that are still
     * being processed; the status distinguishes these cases.
     *
     * @param string $entity_id Same value as used for the upload
     * @return bool False if the file still exists in the RAG and has to be deleted later
     */
    public function deleteFile(string $remote_file_id, string $entity_id): bool
    {
        $this->assertConfigured();

        // Same numeric IDs as used for the upload (the WebGateway expects integers)
        [$application_id, $instance_id, $entity_id_numeric] = self::getNumericIds($entity_id);
        $delete_params = [
            'application_id' => $application_id,
            'instance_id' => $instance_id,
            'entity_id' => $entity_id_numeric,
            'id' => $remote_file_id
        ];

        [$response, $http_code, $error] = $this->request(
            $this->getEndpointUrl(self::ENDPOINT_DELETE),
            json_encode($delete_params),
            ['Content-Type: application/json'],
            60
        );

        if ($response === false) {
            $this->logger->error("RAG deletion failed: cURL error - $error | file=$remote_file_id");
            return false;
        }

        if (in_array($http_code, [200, 204], true)) {
            $this->logger->info("File deleted from RAG: $remote_file_id");
            return true;
        }

        if ($http_code === 400) {
            $status = $this->getFileStatus($remote_file_id, $entity_id);
            if ($status !== null && in_array($status['status'], [self::STATUS_PROCESSING, self::STATUS_PENDING], true)) {
                $this->logger->info("RAG file $remote_file_id is still being processed, deletion postponed");
                return false;
            }
            $this->logger->info("RAG file $remote_file_id not found, treated as deleted");
            return true;
        }

        $this->logger->warning("RAG deletion failed: HTTP $http_code | file=$remote_file_id | " . substr((string) $response, 0, 300));
        return false;
    }

    /**
     * Processing state of a file in the RAG
     *
     * @param string $entity_id Same value as used for the upload
     * @return array{status: string, error: string|null}|null Null if the file is unknown or the RAG is not reachable
     */
    public function getFileStatus(string $remote_file_id, string $entity_id): ?array
    {
        $this->assertConfigured();

        [$application_id, $instance_id, $entity_id_numeric] = self::getNumericIds($entity_id);
        [$response, $http_code, $error] = $this->request(
            $this->getEndpointUrl(self::ENDPOINT_STATUS),
            json_encode([
                'application_id' => $application_id,
                'instance_id' => $instance_id,
                'entity_id' => $entity_id_numeric,
                'id' => $remote_file_id
            ]),
            ['Content-Type: application/json'],
            30
        );

        if ($response === false || $http_code !== 200) {
            $this->logger->debug("RAG status of $remote_file_id not available: HTTP $http_code $error");
            return null;
        }

        $data = json_decode((string) $response, true);
        if (!is_array($data) || !isset($data['status'])) {
            return null;
        }

        return [
            'status' => strtoupper((string) $data['status']),
            'error' => isset($data['error_message']) ? (string) $data['error_message'] : null,
        ];
    }

    /**
     * Numeric application, instance and entity IDs for upload and deletion
     *
     * The WebGateway expects integers, so the configured texts and the entity ID are
     * hashed; upload and deletion must use the same values.
     *
     * @return int[] [application ID, instance ID, entity ID]
     */
    public static function getNumericIds(string $entity_id): array
    {
        $application_id_text = (string) (\platform\AIChatPageComponentConfig::get('rag_application_id') ?: 'ILIAS');
        $instance_id_text = (string) (\platform\AIChatPageComponentConfig::get('rag_instance_id') ?: 'ilias9');

        return [
            abs(crc32($application_id_text)) % 2147483647,
            abs(crc32($instance_id_text)) % 999999,
            abs(crc32($entity_id)) % 2147483647,
        ];
    }

    /**
     * Retrieve the passages relevant to the conversation, without generating an answer
     *
     * @param array $messages OpenAI message format; the last message must be a user message
     * @return array{messages: array, chunks: array}
     * @throws AIChatPageComponentException
     */
    public function augment(array $messages, array $collection_ids): array
    {
        $this->assertConfigured();

        $top_k = (int) (\platform\AIChatPageComponentConfig::get('rag_top_k') ?: self::DEFAULT_TOP_K);

        $payload = [
            'messages' => $messages,
            'collection_ids' => array_values($collection_ids),
            'top_k' => max(1, $top_k)
        ];

        $url = $this->getEndpointUrl(self::ENDPOINT_AUGMENTATION);
        $this->logger->debug("RAG Augmentation Request | collections=" . json_encode($collection_ids) .
            " | messages=" . count($messages) . " | top_k=" . $payload['top_k']);

        [$response, $http_code, $error] = $this->request(
            $url,
            json_encode($payload),
            ['Content-Type: application/json'],
            180
        );

        if ($response === false) {
            $this->logger->error("RAG retrieval failed: cURL error - $error");
            throw new AIChatPageComponentException(self::UNAVAILABLE);
        }

        if ($http_code !== 200) {
            // Reason in the message text: the log format does not print the context array
            $this->logger->error("RAG retrieval failed: HTTP $http_code | " . substr((string) $response, 0, 300));
            if ($http_code === 0 || $http_code >= 500) {
                throw new AIChatPageComponentException(self::UNAVAILABLE, $http_code);
            }
            $lost_collections = self::parseUnauthorizedCollections((string) $response, $collection_ids);
            if ($lost_collections !== null) {
                throw new AIChatPageComponentRAGBindingLostException($lost_collections);
            }
            throw new AIChatPageComponentException("RAG retrieval failed: HTTP $http_code", $http_code);
        }

        $data = json_decode((string) $response, true);
        if (!is_array($data) || !isset($data['messages']) || !is_array($data['messages'])) {
            throw new AIChatPageComponentException("Invalid RAG retrieval response");
        }

        $chunks = is_array($data['chunks'] ?? null) ? $data['chunks'] : [];

        $this->logger->debug("RAG Augmentation Response | chunks=" . count($chunks));

        return [
            'messages' => $data['messages'],
            'chunks' => $chunks
        ];
    }

    /**
     * Collections the RAG rejected because the tenant of the client key has no access
     *
     * The WebGateway reports this as HTTP 400 with "Unauthorized access to collection IDs [...]".
     * If the IDs cannot be read from the message, all requested collections are returned.
     *
     * @param string[] $requested_ids
     * @return string[]|null Null if the response is not such a rejection
     */
    public static function parseUnauthorizedCollections(string $response, array $requested_ids): ?array
    {
        $text = stripslashes($response);
        if (stripos($text, 'Unauthorized access to collection') === false) {
            return null;
        }

        if (preg_match('/Unauthorized access to collection IDs \[([^\]]*)\]/i', $text, $match)) {
            preg_match_all('/[A-Za-z0-9_\-]+/', $match[1], $ids);
            $lost = array_values(array_intersect($ids[0], $requested_ids));
            if (!empty($lost)) {
                return $lost;
            }
        }

        return array_values($requested_ids);
    }

    /**
     * Convert chunks into the source format of api.php and the frontend
     *
     * Sorted by reference index, so source N belongs to citation [cit-(N-1)].
     */
    public static function chunksToSources(array $chunks): array
    {
        usort($chunks, fn($a, $b) => ($a['reference_index'] ?? 0) <=> ($b['reference_index'] ?? 0));

        $sources = [];
        foreach ($chunks as $chunk) {
            $metadata = is_array($chunk['metadata'] ?? null) ? $chunk['metadata'] : [];
            $sources[] = [
                // The WebGateway HTML-encodes file names (e.g. "Getr&#228;nke.pdf")
                'filename' => html_entity_decode((string) ($chunk['filename'] ?? 'unknown'), ENT_QUOTES | ENT_HTML5, 'UTF-8'),
                'page_numbers' => is_array($metadata['page_numbers'] ?? null) ? $metadata['page_numbers'] : [],
                'text' => $chunk['text'] ?? '',
                'url' => $metadata['url'] ?? null,
                'file_id' => $chunk['file_id'] ?? null,
                'collection_id' => $chunk['collection_id'] ?? null,
            ];
        }

        return $sources;
    }

    /**
     * Convert [cit-0] / [cit-0, cit-2] into 1-based references ([1], [1][3])
     */
    public static function convertCitationMarkers(string $text): string
    {
        return preg_replace_callback(
            '/\[\s*(cit-\d+(?:\s*,\s*cit-\d+)*)\s*\]/i',
            static function (array $match): string {
                preg_match_all('/cit-(\d+)/i', $match[1], $numbers);
                return implode('', array_map(fn($n) => '[' . ((int) $n + 1) . ']', $numbers[1]));
            },
            $text
        ) ?? $text;
    }

    private function assertConfigured(): void
    {
        if (self::getApiUrl() === '' || self::getClientKey() === '') {
            throw new AIChatPageComponentException("RAG service not configured (URL or client key missing)");
        }
    }

    private function getEndpointUrl(string $endpoint): string
    {
        $base_url = self::getApiUrl();

        // Accept base URLs that already end with /v1
        if (str_ends_with($base_url, '/v1') && str_starts_with($endpoint, '/v1/')) {
            $endpoint = substr($endpoint, 3);
        }

        return $base_url . $endpoint;
    }

    /**
     * @param array|string $body Multipart fields or JSON
     * @return array{0: string|false, 1: int, 2: string} Response, HTTP status, cURL error
     */
    private function request(string $url, $body, array $headers, int $timeout): array
    {
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_POST, true);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $body);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_HTTPHEADER, array_merge(
            $headers,
            ['Authorization: Bearer ' . self::getClientKey()]
        ));
        curl_setopt($curl, CURLOPT_TIMEOUT, $timeout);
        curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 30);
        // Uploads of some PDFs are aborted by the gateway over HTTP/2 (PROTOCOL_ERROR), not over HTTP/1.1
        curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);

        // Use the bundled CA file if present, otherwise the system CA store
        $plugin = \ilAIChatPageComponentPlugin::getInstance();
        $ca_cert_path = realpath($plugin->getDirectory()) . '/certs/RAMSES.pem';
        if (file_exists($ca_cert_path)) {
            curl_setopt($curl, CURLOPT_CAINFO, $ca_cert_path);
        }

        AIChatPageComponentLLM::applyProxySettings($curl);

        $response = curl_exec($curl);
        $http_code = (int) curl_getinfo($curl, CURLINFO_HTTP_CODE);
        $error = curl_error($curl);
        curl_close($curl);

        return [$response, $http_code, $error];
    }
}
